# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65b62a0c4d0b1fc543e9e704d1d2274ca9c3db573a0ad3bbb71c5c8a17b5c7e73fc33ee08bc077823a7cc0ef5161d632bfdbb5a2d07a054e19360a65ab64674

test:
  secret_key_base: d3334c3f39dda79b8da7b0188f56b0d04225ec56784adeb199cfd8147bf75f9084bea28f9426520d6256e223a880cbbd4dd1d2669996d3f3c7e7791c556d72b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
